//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrIslerWinUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlinanDers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AlinanDers()
        {
            this.Notlar = new HashSet<Not>();
        }
    
        public int Id { get; set; }
        public string DersKodu { get; set; }
        public string OgrNo { get; set; }
        public string Donem { get; set; }
        public int Yil { get; set; }
    
        public virtual Ders Dersler { get; set; }
        public virtual Ogrenci Ogrenciler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Not> Notlar { get; set; }
    }
}
