//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrIslerWinUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ders()
        {
            this.AlinanDersler = new HashSet<AlinanDers>();
        }
    
        public string DersKodu { get; set; }
        public string DersAdi { get; set; }
        public string Donem { get; set; }
        public int Akts { get; set; }
        public int Hds { get; set; }
        public int BKodu { get; set; }
        public int DKodu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlinanDers> AlinanDersler { get; set; }
        public virtual Bolum Bolumler { get; set; }
        public virtual Danisman Danismanlar { get; set; }
    }
}
