//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrIslerWinUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KisiselBilgi
    {
        public string OgrNo { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public string Cinsiyet { get; set; }
        public System.DateTime DTarih { get; set; }
        public string TcKimlik { get; set; }
    
        public virtual Ogrenci Ogrenciler { get; set; }
    }
}
