//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrIslerWinUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Not
    {
        public int Id { get; set; }
        public int SKodu { get; set; }
        public int Notu { get; set; }
        public int AlinanDersId { get; set; }
    
        public virtual AlinanDers AlinanDersler { get; set; }
        public virtual SinavTur SinavTurleri { get; set; }
    }
}
