//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrIslerWinUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogrenci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ogrenci()
        {
            this.AlinanDersler = new HashSet<AlinanDers>();
        }
    
        public string OgrNo { get; set; }
        public int Sinif { get; set; }
        public string PKodu { get; set; }
        public int DKodu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlinanDers> AlinanDersler { get; set; }
        public virtual Danisman Danismanlar { get; set; }
        public virtual KisiselBilgi KisiselBilgiler { get; set; }
        public virtual Program Programlar { get; set; }
    }
}
