//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrIslerWinUI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OgrIslerDbEntities : DbContext
    {
        public OgrIslerDbEntities()
            : base("name=OgrIslerDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AlinanDers> AlinanDersler { get; set; }
        public virtual DbSet<Bolum> Bolumler { get; set; }
        public virtual DbSet<Danisman> Danismanlar { get; set; }
        public virtual DbSet<Ders> Dersler { get; set; }
        public virtual DbSet<KisiselBilgi> KisiselBilgiler { get; set; }
        public virtual DbSet<Kullanici> Kullanicilar { get; set; }
        public virtual DbSet<Not> Notlar { get; set; }
        public virtual DbSet<Ogrenci> Ogrenciler { get; set; }
        public virtual DbSet<Program> Programlar { get; set; }
        public virtual DbSet<SinavTur> SinavTurleri { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
